# Build stage
FROM golang:1.24-alpine AS builder
RUN apk add --no-cache git
WORKDIR /app
COPY ./space-backend-client/go.mod ./
COPY ./space-backend-client/go.sum ./
RUN go mod download
COPY ../space-backend-client/ .
RUN CGO_ENABLED=0 GOOS=linux go build -o main .
EXPOSE 8080
COPY ../space-backend-client/init-container.sh /usr/local/bin/init-container.sh
RUN touch .env
RUN chmod u+w .env
RUN chmod +x /usr/local/bin/init-container.sh
CMD ["/usr/local/bin/init-container.sh"]

