package utils

import "fmt"

const (
	CANNOT_CONNECT_TO_MONGODB = iota
	ERROR_TO_TRY_FIND_MONGODB
	ERROR_WHEN_GENERATE_ACCESS_TOKEN
	ERROR_WHEN_GENERATE_REFRESH_TOKEN
	HTTP_METHOD_NO_ALLOWED
	MISSING_AUTHORIZATION_HEADER
	WRONG_AUTHORIZATION_HEADER_FORMAT
	ACCESS_TOKEN_INVALID_OR_EXPIRED
	REFRESH_TOKEN_INVALID_OR_EXPIRED_1
	REFRESH_TOKEN_INVALID_OR_EXPIRED_2
	CLIENTS_INVALID_REQUEST_DATA
	CLIENTS_MISSING_REQUEST_DATA
	ERROR_TO_CREATE_PASSWORD_HASH
	CANNOT_INSERT_CLIENT_TO_MONGODB
	MISSING_REFRESH_TOKEN_IN_COOKIES
	MIDDLEWARE_REFRESH_TOKEN_INVALID_OR_EXPIRED
	ERROR_TO_UPDATE_REFRESH_TOKEN
	INVALID_USER_ID_FORMAT
	REFRESH_TOKEN_NOT_MATCHING_DATABASE
	ERROR_TO_UPDATE_CLIENT_TO_MONGODB
)

func SendInternalError(internalErrorCode int) string {
	return fmt.Sprintf("Ocorreu um erro interno no servidor. Por favor, tente novamene mais tarde (Cod: %d)", internalErrorCode)
}
